// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_lists.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countTodoListsByUser = `-- name: CountTodoListsByUser :one
SELECT COUNT(*)
FROM todo_lists
WHERE user_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountTodoListsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoListsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodoList = `-- name: CreateTodoList :exec
INSERT INTO todo_lists (id, user_id, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateTodoListParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) error {
	_, err := q.db.ExecContext(ctx, createTodoList,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTodoListByID = `-- name: GetTodoListByID :one
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM todo_lists
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetTodoListByID(ctx context.Context, id string) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoListByID, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTodoListsByUserID = `-- name: GetTodoListsByUserID :many
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM todo_lists
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetTodoListsByUserID(ctx context.Context, userID string) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, getTodoListsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByListID = `-- name: GetTodosByListID :many
SELECT id, user_id, list_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE list_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetTodosByListIDRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ListID      sql.NullString `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetTodosByListID(ctx context.Context, listID sql.NullString) ([]GetTodosByListIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTodosByListIDRow{}
	for rows.Next() {
		var i GetTodosByListIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodoList = `-- name: SoftDeleteTodoList :exec
UPDATE todo_lists
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodoList(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodoList, id)
	return err
}

const updateTodoList = `-- name: UpdateTodoList :exec
UPDATE todo_lists
SET name = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTodoListParams struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoList, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
