// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countTodos = `-- name: CountTodos :one
SELECT COUNT(*)
FROM todos
WHERE deleted_at IS NULL
`

func (q *Queries) CountTodos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByUser = `-- name: CountTodosByUser :one
SELECT COUNT(*)
FROM todos
WHERE user_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountTodosByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosFiltered = `-- name: CountTodosFiltered :one
SELECT COUNT(*)
FROM todos
WHERE deleted_at IS NULL
  AND (? IS NULL OR user_id = ?)
  AND (? IS NULL OR completed = ?)
  AND (? IS NULL OR priority = ?)
  AND (? IS NULL OR due_date >= ?)
  AND (? IS NULL OR due_date <= ?)
`

type CountTodosFilteredParams struct {
	UserID      sql.NullString `json:"user_id"`
	Completed   sql.NullBool   `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDateFrom sql.NullTime   `json:"due_date_from"`
	DueDateTo   sql.NullTime   `json:"due_date_to"`
}

func (q *Queries) CountTodosFiltered(ctx context.Context, arg CountTodosFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosFiltered,
		arg.UserID,
		arg.UserID,
		arg.Completed,
		arg.Completed,
		arg.Priority,
		arg.Priority,
		arg.DueDateFrom,
		arg.DueDateFrom,
		arg.DueDateTo,
		arg.DueDateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, user_id, list_id, title, description, completed, priority, due_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTodoParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ListID      sql.NullString `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Priority,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, list_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE id = ? AND deleted_at IS NULL
`

type GetTodoByIDRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ListID      sql.NullString `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetTodoByID(ctx context.Context, id string) (GetTodoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i GetTodoByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTodosByUserID = `-- name: GetTodosByUserID :many
SELECT id, user_id, list_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTodosByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetTodosByUserIDRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ListID      sql.NullString `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetTodosByUserID(ctx context.Context, arg GetTodosByUserIDParams) ([]GetTodosByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTodosByUserIDRow{}
	for rows.Next() {
		var i GetTodosByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosFiltered = `-- name: GetTodosFiltered :many
SELECT id, user_id, list_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE deleted_at IS NULL
  AND (? IS NULL OR user_id = ?)
  AND (? IS NULL OR completed = ?)
  AND (? IS NULL OR priority = ?)
  AND (? IS NULL OR due_date >= ?)
  AND (? IS NULL OR due_date <= ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTodosFilteredParams struct {
	UserID      sql.NullString `json:"user_id"`
	Completed   sql.NullBool   `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDateFrom sql.NullTime   `json:"due_date_from"`
	DueDateTo   sql.NullTime   `json:"due_date_to"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
}

type GetTodosFilteredRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ListID      sql.NullString `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetTodosFiltered(ctx context.Context, arg GetTodosFilteredParams) ([]GetTodosFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodosFiltered,
		arg.UserID,
		arg.UserID,
		arg.Completed,
		arg.Completed,
		arg.Priority,
		arg.Priority,
		arg.DueDateFrom,
		arg.DueDateFrom,
		arg.DueDateTo,
		arg.DueDateTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTodosFilteredRow{}
	for rows.Next() {
		var i GetTodosFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = ?, description = ?, completed = ?, priority = ?, due_date = ?, updated_at = ?, completed_at = ?, list_id = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	ListID      sql.NullString `json:"list_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Priority,
		arg.DueDate,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ListID,
		arg.ID,
	)
	return err
}
