// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countTodos = `-- name: CountTodos :one
SELECT COUNT(*)
FROM todos
WHERE deleted_at IS NULL
`

func (q *Queries) CountTodos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByUser = `-- name: CountTodosByUser :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTodosByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosFiltered = `-- name: CountTodosFiltered :one
SELECT COUNT(*)
FROM todos
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR user_id = $1)
  AND ($2::boolean IS NULL OR completed = $2)
  AND ($3::varchar IS NULL OR priority = $3)
  AND ($4::timestamp IS NULL OR due_date >= $4)
  AND ($5::timestamp IS NULL OR due_date <= $5)
`

type CountTodosFilteredParams struct {
	UserID    uuid.NullUUID  `json:"user_id"`
	Completed sql.NullBool   `json:"completed"`
	Priority  sql.NullString `json:"priority"`
	FromDate  sql.NullTime   `json:"from_date"`
	ToDate    sql.NullTime   `json:"to_date"`
}

func (q *Queries) CountTodosFiltered(ctx context.Context, arg CountTodosFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosFiltered,
		arg.UserID,
		arg.Completed,
		arg.Priority,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, user_id, title, description, completed, priority, due_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateTodoParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   sql.NullBool   `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Priority,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTodoByID(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTodosByUserID = `-- name: GetTodosByUserID :many
SELECT id, user_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTodosByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetTodosByUserID(ctx context.Context, arg GetTodosByUserIDParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosFiltered = `-- name: GetTodosFiltered :many
SELECT id, user_id, title, description, completed, priority, due_date, created_at, updated_at, completed_at, deleted_at
FROM todos
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR user_id = $1)
  AND ($2::boolean IS NULL OR completed = $2)
  AND ($3::varchar IS NULL OR priority = $3)
  AND ($4::timestamp IS NULL OR due_date >= $4)
  AND ($5::timestamp IS NULL OR due_date <= $5)
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type GetTodosFilteredParams struct {
	UserID    uuid.NullUUID  `json:"user_id"`
	Completed sql.NullBool   `json:"completed"`
	Priority  sql.NullString `json:"priority"`
	FromDate  sql.NullTime   `json:"from_date"`
	ToDate    sql.NullTime   `json:"to_date"`
	Offset    int32          `json:"offset"`
	Limit     int32          `json:"limit"`
}

func (q *Queries) GetTodosFiltered(ctx context.Context, arg GetTodosFilteredParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosFiltered,
		arg.UserID,
		arg.Completed,
		arg.Priority,
		arg.FromDate,
		arg.ToDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = $2, description = $3, completed = $4, priority = $5, due_date = $6, updated_at = $7, completed_at = $8
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   sql.NullBool   `json:"completed"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Priority,
		arg.DueDate,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}
